package com.mt.app.payment.common;

import android.R.integer;

public class Constants {
	public static final int USR_REGISTER=0;//用户注册
	public static final int USR_GET_REGTEXT=1;//获取验证码
 	public static final int USR_LOGIN=2;//用户登录
 	public static final int USR_QUERY_PACKAGE=3;//套餐查询
 	public static final int USR_BIND_PACKAGE=4;//套餐绑定
 	public static final int USR_BASE_CARD_BIND=5;//基卡绑定
 	public static final int USR_BASE_CARD_UNBIND=6;//基卡解绑
 	public static final int USR_CARD_APP_BIND=7;//基卡应用关系绑定
 	public static final int USR_CARD_APP_UNBIND=8;//基卡应用关系解绑
 	public static final int USR_CARD_APP_QUERY=9;//应用列表查询
	public static final int USR_QUERY_CARD=10; //查询基卡信息
	public static final int USR_UPDATE_PASS=11;//修改密码
	public static final int USR_UPDATE_CARD=12;//基卡修改
	public static final int USR_GET_VERIFY=13;//登录后获取验证码
	public static final int USR_SUBMIT_VERIFY=14;//提交验证码
	public static final int USR_OBTAIN_DIS_QUERY=15;//查询已领的优惠券列表       10
	public static final int USR_COUPON_LIST=16;//优惠券列表查询    11
	public static final int USR_COUPON_DETAILS=17;//优惠券详情    12
	public static final int USR_SALE_LIST=18;//折扣商家列表查询    14
	public static final int USR_SALE_DETAILS=19;//折扣商家详情查询    15
	public static final int USR_APPLY_COUPON=20;//优惠券领取    17
	public static final int USR_QUERY_PONIT=21;//积分查询    21
	public static final int USR_CARD_APP_BIND_QUERY=22;//用户已绑定的应用列表查询    21
	public static final int USR_APP_BIND_DETAIL_QUERY=23;//用户已绑定的应用详情查询    22
	public static final int USR_INFO_QUERY=24;//用户详情查询    22
	public static final int USR_COUPON_DETAILS_HAVE=25;//用户已领用的优惠券详情    12
	public static final int USR_USER_INFO_UPDATE=26;//修改用户信息    12
	public static final int USR_NEAR_MERCHANT=27;//查询附近商户    12
	public static final int USR_MERCHANT_COUPON_NOLOGIN=28;//某商户 优惠券查询(登陆前)
	public static final int USR_MERCHANT_COUPON_LOGIN=29;//某商户 优惠券查询(登陆后)
	public static final int USR_MERCHANT_DIS=30;//某商户 折扣查询
	public static final int USR_MERCHANT_LSIT_CARE=31;//查询用户所关注的商家列表
	public static final int USR_MERCHANT_OPT_CARE=32;//增加和取消商户关注
	public static final int USR_COUPONS_SEARCH = 33;//优惠券搜索
	public static final int USR_MERCH_SRARCH = 34;//折扣商家搜索
 	public static final int USR_APP_UPDATE=35;//下载更新
 	public static final int USR_FORGOTPWD=36;//找回密码
 	public static final int USR_AD = 37;//广告
 	public static final int USR_COUPONR_RETURN = 38;//优惠券退领
 	public static final int USR_MERCHANT_DETAILS = 39 ; //商户详情查询
 	public static final int USR_APP_DEFAULT_SET = 40 ;	// 设置默认支付应用
 	public static final int USR_CHANGEPHONE = 41 ;		// 修改手机号码
 	
	public static final String JSONTYPE_OBJECT="object";//json传回为object类型
 	public static final String JSONTYPE_ARRAY="array";//json传回为array类型
 	
 	
 	public static final int MESSID_USR_REGISTER = 0;//用户注册
	public static final int MESSID_GET_REGTEXT = 1;//获取验证
 	public static final int MESSID_USR_LOGIN = 2;//用户登录
 	public static final int MESSID_QUERY_PACKAGE = 3;//套餐查询
 	public static final int MESSID_BIND_PACKAGE = 4;//套餐绑定
 	public static final int MESSID_BASE_CARD_BIND = 5;//基卡绑定
 	public static final int MESSID_BASE_CARD_UNBIND = 6;//基卡解绑
 	public static final int MESSID_CARD_APP_BIND = 7;//基卡应用关系绑定
 	public static final int MESSID_CARD_APP_UNBIND = 8;//基卡应用关系解绑
 	public static final int MESSID_CARD_APP_QUERY=9;//应用列表查询
 	public static final int MESSID_QUERY_CARD=10;//查询基卡信息
 	public static final int MESSID_UPDATE_PASS=11;//修改密码
 	public static final int MESSID_UPDATE_CARD=12;//基卡修改
 	public static final int MESSID_GET_VERIFY=13;//登录后获取验证码
 	public static final int MESSID_SUBMIT_VERIFY=14;//提交验证码
 	public static final int MESSID_OBTAIN_DIS_QUERY=15;//查询已领的优惠券        10
 	public static final int MESSID_COUPON_LIST=16;//优惠券列表查询    11
	public static final int MESSID_COUPON_DETAILS=17;//优惠券详情    12
	public static final int MESSID_SALE_LIST=18;//折扣商家列表查询    14
	public static final int MESSID_SALE_DETAILS=19;//折扣商家详情查询    15
	public static final int MESSID_APPLY_COUPON=20;//优惠券领取    17
	public static final int MESSID_QUERY_PONIT=21;//积分查询    21
	public static final int MESSID_CARD_APP_BIND_QUERY=22;//用户已绑定的应用列表查询    22
	public static final int MESSID_APP_BIND_DETAIL_QUERY=23;//用户已绑定的应用详情查询    23
	public static final int MESSID_INFO_QUERY=24;//用户详情查询    22  
	public static final int MESSID_COUPON_DETAILS_HAVE=25;//用户已领用的优惠券详情   
	public static final int MESSID_USER_INFO_UPDATE=26;//修改用户信息
	public static final int MESSID_NEAR_MERCHANT=27;//查询附近商户
	public static final int MESSID_MERCHANT_COUPON_NOLOGIN=28;//某商户 优惠券查询(登陆前)
	public static final int MESSID_MERCHANT_COUPON_LOGIN=29;//某商户 优惠券查询(登陆后)
	public static final int MESSID_MERCHANT_DIS=30;//某商户 折扣查询
	public static final int MESSID_MERCHANT_LSIT_CARE=31;//查询用户所关注的商家列表
	public static final int MESSID_MERCHANT_OPT_CARE=32;//增加和取消商户关注
	public static final int MESSID_COUPONS_SEARCH = 33;//优惠券搜索
	public static final int MESSID_MERCH_SRARCH = 34;//折扣商家搜索
	public static final int MESSID_APP_UPDATE=35;//下载更新
	public static final int MESSID_FORGOTPWD=36;//找回密码
	public static final int MESSID_AD = 37;//广告
	public static final int MESSID_COUPONR_RETURN = 38;//优惠券退领
	public static final int MESSID_MERCHANT_DETAILS = 39 ; //商户详情查询
	public static final int MESSID_APP_DEFAULT_SET = 40 ;		// 设置默认支付应用
	public static final int MESSID_CHANGEPHONE = 41 ;		// 修改手机号码
	
	
   /* public static final String URL_USR_REGISTER = "Succ";//用户注册
	public static final String URL_GET_REGTEXT = "Succ";//获取验证
 	public static final String URL_USR_LOGIN = "Succ";//用户登录
 	public static final String URL_QUERY_PACKAGE = "Busi";//套餐查询
 	public static final String URL_BIND_PACKAGE = "Succ";//套餐绑定
 	public static final String URL_BASE_CARD_BIND = "Succ";//基卡绑定
 	public static final String URL_BASE_CARD_UNBIND = "Succ";//基卡解绑
 	public static final String URL_CARD_APP_BIND = "Succ";//基卡应用关系绑定
 	public static final String URL_CARD_APP_UNBIND = "Succ";//基卡应用关系解绑
 	public static final String URL_CARD_APP_QUERY= "Mpay";//应用列表查询
 	public static final String URL_QUERY_CARD="Card";//查询基卡信息
 	public static final String URL_UPDATE_PASS="Succ";//修改密码
 	public static final String URL_UPDATE_CARD="Succ";//基卡修改
 	public static final String URL_GET_VERIFY="Succ";//登录后获取验证码
 	public static final String URL_SUBMIT_VERIFY="Succ";//提交验证码
 	public static final String URL_OBTAIN_DIS_QUERY="Appl";//查询已领的优惠券          10
 	public static final String URL_COUPON_LIST="Coup";//优惠券列表查询    11
	public static final String URL_COUPON_DETAILS="ApplDeta";//列表优惠券详情    12
	public static final String URL_SALE_LIST="Sale";//折扣商家列表查询    14
	public static final String URL_SALE_DETAILS="Deta";//折扣商家详情查询    15
	public static final String URL_APPLY_COUPON="Succ";//优惠券领取    17
	public static final String URL_QUERY_PONIT="Point";//积分查询   
	public static final String URL_CARD_APP_BIND_QUERY="getMpayAppsByUser";//用户已绑定的应用列表查询      22
	public static final String URL_APP_BIND_DETAIL_QUERY="mpayUserAppView";//用户已绑定的应用应用详情      
	public static final String URL_INFO_QUERY="mpayUserView";//用户详情查询    22  
	public static final String URL_COUPON_DETAILS_HAVE="ApplDetaHave";//用户已领用的优惠券详情    22
*/ 	//已经调试通过的url
 	public static final String URL_USR_REGISTER = "mpayFront/reg";//用户注册
	public static final String URL_GET_REGTEXT = "mpayFront/getCode";//获取验证
 	public static final String URL_USR_LOGIN = "mpayFront/j_spring_security_check";//用户登录
 	public static final String URL_QUERY_PACKAGE = "mpayFront/getAllPkg";//套餐查询
 	public static final String URL_BIND_PACKAGE = "mpayFront/bindBusiPackage";//套餐绑定
 	public static final String URL_BASE_CARD_BIND = "mpayFront/bindBaseCard";//基卡绑定
 	public static final String URL_BASE_CARD_UNBIND = "mpayFront/bindBaseCard";//基卡解绑
 	public static final String URL_CARD_APP_BIND = "mpayFront/bindMpayApp";//基卡应用关系绑定
 	public static final String URL_CARD_APP_UNBIND = "mpayFront/bindMpayApp";//基卡应用关系解绑
 	public static final String URL_CARD_APP_QUERY= "mpayFront/getAllMpayApps";//应用列表查询
 	public static final String URL_QUERY_CARD="mpayFront/getAllBaseCardOnUser";//查询基卡信息
 	public static final String URL_UPDATE_PASS="mpayFront/updateUserPassword";//修改密码
 	public static final String URL_UPDATE_CARD="mpayFront/updateBindBaseCard";//基卡修改
 	public static final String URL_GET_VERIFY="mpayFront/getCodeByLogin";//登录后获取验证码
 	public static final String URL_SUBMIT_VERIFY="mpayFront/checkValidateCode";//提交验证码
 	public static final String URL_COUPON_LIST="mobile/coupon/actListByMerchAct";//优惠券列表查询    11
	public static final String URL_COUPON_DETAILS="mobile/coupon/actView/list";//优惠券详情    12
	public static final String URL_SALE_LIST="mobile/coupon/merchMpayDiscountList/list";//折扣商家列表查询    14
	public static final String URL_SALE_DETAILS="mobile/coupon/merchMpayDiscountView/list";//折扣商家详情查询    15
	public static final String URL_APPLY_COUPON="mobile/coupon/couponReceive";//优惠券领取    17
	public static final String URL_QUERY_PONIT="mobile/coupon/creditsView";//积分查询    21
	public static final String URL_CARD_APP_BIND_QUERY="mpayFront/getMpayAppsByUser";//用户已绑定的应用列表查询      22
	public static final String URL_APP_BIND_DETAIL_QUERY="mpayFront/mpayUserAppView";//用户已绑定的应用详情     23
	public static final String URL_INFO_QUERY="mpayFront/mpayUserView";//用户详情查询    22  
	public static final String URL_COUPON_DETAILS_HAVE="mobile/coupon/couponJournalView/list";//用户已领用的优惠券详情    22
 	public static final String URL_OBTAIN_DIS_QUERY="mobile/coupon/receiveActListByMerchAct";//查询已领的优惠券列表          10
 	public static final String URL_USER_INFO_UPDATE="mpayFront/updateUserPassword";//修改用户信息          10
 	public static final String URL_NEAR_MERCHANT="mobile/coupon/getNearMerchant/list";//查询附近商户
 	public static final String URL_MERCHANT_COUPON_NOLOGIN="mobile/coupon/getMerchantActs/list";//某商户 优惠券查询(登陆前)
	public static final String URL_MERCHANT_COUPON_LOGIN="mobile/coupon/getMerchantActsByLogin/list";//某商户 优惠券查询(登陆后)
	public static final String URL_MERCHANT_DIS="mobile/coupon/getMerchMpayDiscountByMerchant/list";//某商户 折扣查询
	public static final String URL_MERCHANT_LSIT_CARE="mobile/coupon/userCareMerchListByLoginUser/list";//查询用户所关注的商家列表
	public static final String URL_MERCHANT_OPT_CARE="mpayFront/careMerchants";//增加和取消商户关注
	public static final String URL_COUPONS_SEARCH = "mobile/coupon/queryRequirementActByMerchAct/list";//优惠券搜索
	public static final String URL_MERCH_SRARCH = "mobile/coupon/queryMerchMpayDiscountByRequirement/list";//折扣商家搜索
	public static final String URL_APP_UPDATE="mobile/coupon/versionReplace";//下载更新
	public static final String URL_FORGOTPWD="mpayFront/getNewPasswordByEmail";//找回密码
	public static final String URL_AD = "mobile/coupon/getTopContent";//广告
	public static final String URL_COUPONR_RETURN = "mobile/coupon/couponReturn";//优惠券退领
	public static final String URL_MERCHANT_DETAILS = "mobile/coupon/getMerchDetail" ; //商户详情查询
	public static final String URL_APP_DEFAULT_SET = "mpayFront/defaultApp" ;		// 设置默认支付应用
	public static final String URL_CHANGEPHONE = "mpayFront/updateMobile" ;		// 修改手机号码
}
