/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_test_jni_JniClient */
#ifndef _Included_com_example_jni_test_jni_JniClient
#define _Included_com_example_jni_test_jni_JniClient
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    AutoRun
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_jni_1test_jni_JniClient_AutoRun(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_open_file
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1open_1file(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_close_file
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1close_1file(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_reader_open
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1reader_1open(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_reader_close
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1reader_1close(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_card_connect
 * Signature: (I)Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1card_1connect(
		JNIEnv *, jclass, jint);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_card_disconnect
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1card_1disconnect(
		JNIEnv *, jclass);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_mifare_auth
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1mifare_1auth(
		JNIEnv *, jclass, jint, jstring, jstring, jint);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_mifare_read
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1mifare_1read(
		JNIEnv *, jclass, jint, jstring);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_mifare_write
 * Signature: (ILjava/lang/String;)I
 */JNIEXPORT jint JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1mifare_1write(
		JNIEnv *, jclass, jint, jstring);
/*
 * Class:     com_example_jni_test_jni_JniClient
 * Method:    picc_iso_apdu
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_jni_1test_jni_JniClient_picc_1iso_1apdu(
		JNIEnv *, jclass, jstring);

#endif
